### ISSUE TITLE
Loading multidimentional images

### ISSUE THREAD

**Issue by bioimage-analysis** [ahnlabb/BioformatsLoader.jl#1]
Hi,
First thank you for sharing your bioformatsloader, I'm new to Julia and I found it very useful for my work. I changed the `open_img` function so it will load multidimentional stack of images (XYCZT) and I was wondering if you would be interesting in updating your repository with it?

**Comment by ahnlabb** [comment]
Hi,
I'm glad that it has been of use to you! I actually made a small ad hoc change a while back because I also needed that feature but I've been really busy this past month and haven't had time to update the repository.
It is a much needed feature so it would be great if you shared your patch here or made a pull request with the changed code!

**Comment by ahnlabb** [comment]
Fixed by #2
