### ISSUE TITLE
GetMethodID failure?

### ISSUE THREAD

**Issue by mmattocks** [ahnlabb/BioformatsLoader.jl#5]
Hi folks,
I am trying to use this package to open some .lifs. In doing so, I have encountered a weird error- it seems that create_service is failing for me at the jcall

`    service = jcall(factory, "getInstance", JService, (JClass,), cls)`

with the error

```
Exception in thread "main" java.lang.NoSuchMethodError: getInstance
ERROR: JavaCall.JavaCallError("Error calling Java: java.lang.NoSuchMethodError: getInstance")
```

implying that there is no getInstance method with the ServiceFactory for the given signature, I guess. I don't see what's wrong with the jcall, does anyone know why this might be failing?

**Comment by ahnlabb** [comment]
Looks like it could be an issue with the `bioformats_package.jar` file. It should be downloaded on installation. To rerun the build process you can use:
```
julia>]build BioformatsLoader
```
from the julia prompt. To manually check that the dependencies are downloaded you can do:
``` julia
import BioformatsLoader
isfile(BioformatsLoader.get_bf_path())
```
We should probably do this in the `init` function so that people get a more sensible error.

**Comment by mmattocks** [comment]
Many thanks for your time!! This does indeed seem to have been the issue- I had cloned from github, built with the build.jl script in /deps, and added with "dev", but it seems something must have gone wrong with this. Adding directly from github url works fine.
